/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.sbm;

import io.vavr.collection.List;
import io.vavr.collection.SortedSet;
import io.vavr.collection.TreeSet;

import java.math.BigDecimal;


public class LiveOrderBoardService {

    // immutable Set using VAVR
    private SortedSet<Order> orderBook = TreeSet.empty(Order.NATURAL_ORDER);

    public boolean register(final Order order) {
        if (orderBook.contains(order)) return false;
        this.orderBook = orderBook.add(order.normalized());
        return true;
    }

    public boolean cancel(final Order order) {
        if (!orderBook.contains(order)) return false;
        this.orderBook = orderBook.remove(order);
        return true;
    }

    public List<SummaryEntry> summary(Order.Type type) {
        if (type == null) return List.of();
        return orderBook
                .filter(o -> type.equals(o.getType()))
                .toList()
                .groupBy(Order::getPrice)
                .map(t -> new SummaryEntry(t._2.map(Order::getQuantity).reduce(BigDecimal::add), t._1).normalized())
                .toList();
    }
}
