/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.sbm;

import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;


public class LiveOrderBoardService {

    //XXX no-multi-threaded
    private Set<Order> orderBook = new TreeSet<>(Comparator.comparing(Order::getPrice));

    public boolean register(final Order order) {
        return orderBook.add(order.normalized());
    }


    public boolean someLibraryMethod() {
        return true;
    }

    public List<Order> summary(Order.Type type) {
        return orderBook.stream().filter(o -> o.getType().equals(type)).collect(Collectors.toList());
    }
}
